name: Go Dependency Submission
on:
  workflow_dispatch:
  # release:
  #   types: [ published ]

# cancel in progress runs for the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# The API requires write permission on the repository to submit dependencies
permissions:
  contents: write
  security-events: read

jobs:
  go-action-detection:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Extract Go version from go.mod
        id: go-version
        run: echo "version=$(grep '^go ' go.mod | awk '{print $2}')" >> $GITHUB_OUTPUT

      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version: ${{ steps.go-version.outputs.version }}

      - name: Fix cache permissions
        run: |
          chmod -R 0755 \
          ~/go/pkg/mod \
          ~/.cache/go-build \
          ~/.cache/golangci-lint \
          ~/.cache/buf/

      - name: Set up Go cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-amd64-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-amd64-go-

      - name: Get dependencies
        run: go mod download

      - name: run build
        run: make

      - name: Run snapshot action
        uses: actions/go-dependency-submission@f35d5c9af13ce9cc32f7930b171e315e878f6921 # v2
        with:
          go-mod-path: go.mod
          go-build-target: bin/srt
